### ISSUE TITLE
drive.google.com refused to connect.

### ISSUE THREAD

**Issue by nde-agridea** [fuhrmanator/plantuml-gizmo#1]
**Bug description**
When I start a new PlantUML Gizmo in google docs, it shows the error message 'drive.google.com refused to connect.'

**To Reproduce**
1. Create new Doc
2. Click on Addons --> PlantUml Gizmo --> Start
3. See error

**Screenshots**
![Screenshot 2020-09-24 102117](https://user-images.githubusercontent.com/13120422/94119915-cb9a9b00-fe4f-11ea-8a50-1a1898ff3421.png)

**Which add-on**
- PlantUML Gizmo for Google Docs

**How you installed the add-on**
- G Suite Marketplace

**Desktop (please complete the following information):**
 - OS: Windows 10.0.18363 
 - Browser: Chrome 85.0.4183.121
 - Version 15 (2019-11-22)

**Comment by fuhrmanator** [comment]
Thanks for the detailed bug report. I am not able to reproduce this on two different accounts. 

Can you try disabling your extensions in Chrome (or connect in an incognito tab?) to see if maybe it's a problem with cookies and/or extensions?

Has it worked before for you?

**Comment by fuhrmanator** [comment]
@nde-agridea if you can provide more info so I can help, I will be happy to re-open
