### ISSUE TITLE
Can not use extension to insert diagrams: ScriptError: Invalid image data.

### ISSUE THREAD

**Issue by Hart-Z** [fuhrmanator/plantuml-gizmo#2]
**Describe the bug**
When I tried to insert new diagrams, it pops up "ScriptError: Invalid image data." 

**To Reproduce**
1. Start extension
2. Insert new Diagram
3. Getting "ScriptError: Invalid image data."  error

**Expected behavior**
Generate Diagrams and insert in doc

**Which add-on**
- PlantUML Gizmo for Google Docs
- PlantUML Gizmo for Google Slides

**How you installed the add-on**
- G Suite Marketplace

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome

**Comment by awwaiid** [comment]
I just started getting this on all diagram-insert button presses too. Linux / Firefox. The sidebar preview updates/shows without issue.

**Comment by fuhrmanator** [comment]
I'll try to look at this! I suspect it's a change at plantuml.com web service (I haven't modified the code at Google in more than a year).

**Comment by fuhrmanator** [comment]
Thanks everyone for their patience. I'm stuck trying to debug this (I can't find the logs for my `Logger.log` debug output with the latest Google Cloud jungle). I created a question here: https://stackoverflow.com/questions/75226575/how-to-view-logs-in-a-test-deployment

**Comment by fuhrmanator** [comment]
Ok, I've made some progress - it's something related to PlantUML images.

Try a test in Google Docs: **Insert > Image > By URL**. In the dialog for the URL, paste `https://www.plantuml.com/plantuml/img/SyfFqhLppCbCJbMmKiX8pSd91m00` (it's the default image). It displays properly. 

![image](https://user-images.githubusercontent.com/7606540/214416900-f070aa19-6384-455c-bf57-cfbd86d174d3.png)

However, when I click Insert, the result in the Google Docs is bad:

![image](https://user-images.githubusercontent.com/7606540/214417363-971236d1-80e1-412c-94c1-de2224b7fb02.png)

**Comment by fuhrmanator** [comment]
I opened https://github.com/plantuml/plantuml-server/issues/254 and referred to this issue.

**Comment by arnaudroques** [comment]
> Ok, I've made some progress - it's something related to PlantUML images.

Maybe a security issue on Google Docs side?
Those images are regular PNG images. Or maybe it's because the URL does not end with `.png` ?

Keep us informed!

**Comment by fuhrmanator** [comment]
Arnaud Roques [confirmed ](https://github.com/plantuml/plantuml-server/issues/254#issuecomment-1403405281) it's a problem on PlantUML.com, which recently began serving WEBP instead of true PNG images. My logs for the add-on in Google's cloud show the problem started last Sunday. WEBP images are compatible with most modern browsers, but sadly not compatible with Google Docs (it's an unsupported format for images). That is why the preview works OK (it's an image rendered by the browser). 

I tried to find a way to convert them (server side) and it's not something simple. The Google Apps Script back-end is Rhino-like javascript and there's no easy way to use npm or other common libraries. In a browser, it's very easy with an HTML canvas to convert WEBP to PNG. 

If anyone has ideas, please don't hesitate to share here!

So, unfortunately PlantUML Gizmo will be unusable until PlantUML.com's hosting service can be set to serve PNGs again.

**Comment by fuhrmanator** [comment]
Following the problem of server-side conversion of WEBP to PNG, ChatGPT gave me the following suggestion using [Jimp](https://github.com/oliver-moran/jimp):

```javascript
const Jimp = require('jimp');

function convertWebpToPng(blob) {
    return new Promise((resolve, reject) => {
        Jimp.read(blob, (err, image) => {
            if (err) {
                reject(err);
            } else {
                image.getBuffer(Jimp.MIME_PNG, (err, buffer) => {
                    if (err) {
                        reject(err);
                    } else {
                        resolve(buffer);
                    }
                });
            }
        });
    });
}
```

But to use npm in an add-on, I believe it would be necessary to convert the whole project to Cloud Run (which is not trivial): https://codelabs.developers.google.com/codelabs/workspace-add-on-nodejs-cloudrun

**Comment by arnaudroques** [comment]
I'm really sorry about all this: our host is still working on rolling back to PNG...
I'm not sure why it is taking so long

**Comment by arnaudroques** [comment]
Ok, we've set up a temporary workaround which should just work.
Can you try and tell us?
Thanks!

**Comment by fuhrmanator** [comment]
Thanks for letting us know what's happening.

PlantUML Gizmo uses a (legacy?) url with `/img/` such as [this](https://www.plantuml.com/plantuml/img/SoWkIImgAStDuNBCoKnELT2rKt3AJx9IS2mjoKZDAybCJYp9pCzJ24ejB4qjBk42oYde0jM05MDHLLoGdrUSoeLkM5u-K5sHGY9MGw6ARNHryQb66EwGcfS2T300) and it to just re-direct to PlantUML's main page (invalid url?). So it's not a good workaround - it's the same result when you try to insert an image.

However, it appears that specifying a url with `/png/` such as https://www.plantuml.com/plantuml/png/SoWkIImgAStDuNBCoKnELT2rKt3AJx9IS2mjoKZDAybCJYp9pCzJ24ejB4qjBk42oYde0jM05MDHLLoGdrUSoeLkM5u-K5sHGY9MGw6ARNHryQb66EwGcfS2T300 then according to exifinfo.org it's a PNG file (and should work).

I can change Gizmo to use '/png/' but would rather not make a change to the (legacy) behavior if this fix is temporary. Will the `/img/` URLs return to PNG?

**Comment by arnaudroques** [comment]
> PlantUML Gizmo uses a (legacy?) url with `/img/`

Ok, we've just fix it.
Is it working better? Thx!

**Comment by fuhrmanator** [comment]
PlantUML Gizmo is now inserting images again (at least for me). Thanks for your help, @arnaudroques.
